### ISSUE TITLE
@font-face and $baseFontFamily

### ISSUE THREAD

**Issue by betacar** [mjonuschat/bootstrap-sass-rails#6]
After the `@import` of `twitter/bootstrap/variables`, `twitter/bootstrap/mixins` and `twitter/bootstrap/type`, and the `@font-face` declaration, the `$baseFontFamily` value cannot be overwritten. Is still having the default value, even when I recompile de files and clean the cache.

**Comment by mjonuschat** [comment]
Could you show me the code you are using? 

$baseFontSize is declared as a default value, so using something along the lines of

``` scss
$baseFontSize: 12px;
@import 'twitter/bootstrap/variables';
@import 'twitter/bootstrap/mixins';
@import 'twitter/bootstrap/type';
```

should work.

**Comment by betacar** [comment]
Is not $baseFontSize. I rearrenged the the order of the `@import`'s and it does not work. Here is the code:
`font.css.scss` file

```
// @font-face
@font-face {
  font-family: "Segoe UI";
  src: url("segoeuib-webfont.eot");
  src: url("segoeuib-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeuib-webfont.woff") format("woff");
  src: url("segoeuib-webfont.ttf") format("truetype");
  src: url("segoeuib-webfont.svg#SegoeUINegreta") format("svg");
  font-weight: bold;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("segoeui-webfont.eot");
  src: url("segoeui-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeui-webfont.woff") format("woff");
  src: url("segoeui-webfont.ttf") format("truetype");
  src: url("segoeui-webfont.svg#SegoeUINormal") format("svg");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("segoeuii-webfont.eot");
  src: url("segoeuii-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeuii-webfont.woff") format("woff");
  src: url("segoeuii-webfont.ttf") format("truetype");
  src: url("segoeuii-webfont.svg#SegoeUICursiva") format("svg");
  font-weight: normal;
  font-style: oblique;
}

@font-face {
  font-family: "Segoe UI";
  src: url("segoeuil-webfont.eot");
  src: url("segoeuil-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeuil-webfont.woff") format("woff");
  src: url("segoeuil-webfont.ttf") format("truetype");
  src: url("segoeuil-webfont.svg#SegoeUILight") format("svg");
  font-weight: 100;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("segoeuiz-webfont.eot");
  src: url("segoeuiz-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeuiz-webfont.woff") format("woff");
  src: url("segoeuiz-webfont.ttf") format("truetype");
  src: url("segoeuiz-webfont.svg#SegoeUINegretacursiva") format("svg");
  font-weight: bold;
  font-style: oblique;
}

$baseFontFamily: "Segoe UI", Helvetica, Arial, sans-serif;

@import "twitter/bootstrap/variables";
@import "twitter/bootstrap/mixins";
@import "twitter/bootstrap/type";
```

And the head of the `application.css.scss` file:

```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the top of the
 * compiled file, but it's generally better to create a new file per style scope.
 *
 *= require_self
 *= require twitter/bootstrap
*/
@import "fonts";
```

I did make some test without the `*=requiere twitter/bootstrap` and it does overwrite the $baseFontFamily variable.

**Comment by betacar** [comment]
Doing a fast search in the compiled `application.css.scss` file, the default `font-family`appears in four places:

```
/* line 9, ../../../../../../.rvm/gems/ruby-1.9.3-p125@qeu/gems/bootstrap-sass-rails-2.0.1.2/vendor/assets/stylesheets/twitter/bootstrap/_scaffolding.scss */
body {
  margin: 0;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  ...
}
...
/* line 9, ../../../../../../.rvm/gems/ruby-1.9.3-p125@qeu/gems/bootstrap-sass-rails-2.0.1.2/vendor/assets/stylesheets/twitter/bootstrap/_type.scss */
p {
  margin: 0 0 9px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  ...
}
...
/* line 50, ../../../../../../.rvm/gems/ruby-1.9.3-p125@qeu/gems/bootstrap-sass-rails-2.0.1.2/vendor/assets/stylesheets/twitter/bootstrap/_forms.scss */
input,
button,
select,
textarea {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  ...
}
...
/* line 123, ../../../../../../.rvm/gems/ruby-1.9.3-p125@qeu/gems/bootstrap-sass-rails-2.0.1.2/vendor/assets/stylesheets/twitter/bootstrap/_navbar.scss */
.navbar-search .search-query {
  padding: 4px 9px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  ...
}
...
```

**Comment by mjonuschat** [comment]
Ok, according to you example this problem originates due mixing Sass and AssetPipeline include function which have different scopes and access to variables:

Given your example files what happens:
1. Sprockets evaluates = require_self  
   The Sass compiler gets started, imports fonts.css.scss and set the variables, imports the bootstrap partials and outputs the @font-face setup and the type definitions based on Twitter Bootstrap - enhanced with SegoeUI since in this scope the override for $baseFontFamily is available
2. Sprockets goes on and evaluates = require_tree .  
   Sprockets reads in all files in you assets directory (including fonts.css.scss), starts the Sass compiler i this scope and generates the font and type definitions again, correctly replacing $baseFontFamily with SegoeUI since it has access to the overridden $baseFontFamily
3. Sprockets goes on and evaluates = require twitter/bootstrap  
   Sprockets reads the file, starts the Sass compiler. All the Bootstrap partials get required and the compilation starts. In this scope there's no access to the overridden $baseFontFamily Variable, so the defaults from Twitter Bootstrap are being used. 
   Here we get "Helvetica Neue" and stuff.

In Development mode the browser will load three assets in this order :
1. application.css -> correct font definitions
2. fonts.css -> correct font definitions
3. bootstrap.css -> default font defitions

So the bootstrap.css overrides all your previous definitions.

Removing duplication and scope problems gets you the results you want:

**fonts.css.scss**

``` scss
// @font-face
@font-face {
  font-family: "Segoe UI";
  src: url("segoeuib-webfont.eot");
  src: url("segoeuib-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeuib-webfont.woff") format("woff");
  src: url("segoeuib-webfont.ttf") format("truetype");
  src: url("segoeuib-webfont.svg#SegoeUINegreta") format("svg");
  font-weight: bold;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("segoeui-webfont.eot");
  src: url("segoeui-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeui-webfont.woff") format("woff");
  src: url("segoeui-webfont.ttf") format("truetype");
  src: url("segoeui-webfont.svg#SegoeUINormal") format("svg");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("segoeuii-webfont.eot");
  src: url("segoeuii-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeuii-webfont.woff") format("woff");
  src: url("segoeuii-webfont.ttf") format("truetype");
  src: url("segoeuii-webfont.svg#SegoeUICursiva") format("svg");
  font-weight: normal;
  font-style: oblique;
}

@font-face {
  font-family: "Segoe UI";
  src: url("segoeuil-webfont.eot");
  src: url("segoeuil-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeuil-webfont.woff") format("woff");
  src: url("segoeuil-webfont.ttf") format("truetype");
  src: url("segoeuil-webfont.svg#SegoeUILight") format("svg");
  font-weight: 100;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("segoeuiz-webfont.eot");
  src: url("segoeuiz-webfont.eot?#iefix") format("embedded-opentype");
  src: url("segoeuiz-webfont.woff") format("woff");
  src: url("segoeuiz-webfont.ttf") format("truetype");
  src: url("segoeuiz-webfont.svg#SegoeUINegretacursiva") format("svg");
  font-weight: bold;
  font-style: oblique;
}
```

**application.css.scss**

``` scss

/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the top of the
 * compiled file, but it's generally better to create a new file per style scope.
 *
 *= require_self
 */

$baseFontFamily: "Segoe UI", Helvetica, Arial, sans-serif;

@import "fonts";
@import "twitter/bootstrap";
```
